[package]
name = "cmplx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed = "1.23.0"
ndarray = "0.15.6"
num = "0.4.0"
plotters = "0.3.4"
#plotters-cairo = "0.3.2"
polars = "0.27.2"
